import '@/app/globals.css';
import 'swiper/css';
import 'swiper/css/pagination';

import classNames from 'classnames';
import { Inter } from 'next/font/google';
import { Suspense } from 'react';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      className={classNames(inter.className)}
      suppressHydrationWarning={true}
    >
      <body className={classNames('antialiased')}>
        <Suspense fallback={null}>{children}</Suspense>
      </body>
    </html>
  );
}
